"""Document rendering.

The assertions that matter are the complex-script ones: `w:cs` and `w:szCs` on
every run. Without them Thai renders in a substitute font at the wrong size,
and nothing on a developer machine with Sarabun installed will show it.
"""

from __future__ import annotations

import uuid
import zipfile
from pathlib import Path

import pytest
from docx import Document
from lxml import etree

from sarai import docgen
from sarai.docgen import fonts
from sarai.models import MinutesJSON

W = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"

MINUTES = MinutesJSON.model_validate(
    {
        "title": "ประชุมทีมผลิตภัณฑ์ — สรุป Q3",
        "meeting_date": "2026-08-14",
        "attendees": [{"name": "คุณสมชาย", "role": "Product lead"}, {"name": "คุณมาลี"}],
        "summary": "ที่ประชุมทบทวนความคืบหน้าไตรมาส 3 และการ deploy ระบบใหม่",
        "agenda": ["ทบทวน roadmap", "PDPA"],
        "discussion": [{"topic": "การ deploy", "points": ["QA ยังไม่ผ่าน"], "speakers": ["คุณสมชาย"]}],
        "decisions": [{"decision": "เลื่อน Wallet MVP", "rationale": "รอทีมออกแบบ"}],
        "action_items": [
            {
                "task": "ส่งเอกสาร PDPA",
                "owner": "คุณมาลี",
                "due": "2026-08-21",
                "source_quote": "เดี๋ยวจะส่งให้ภายในวันศุกร์",
            }
        ],
        "open_questions": ["ใครดูแล subscription flow"],
        "next_meeting": "สัปดาห์หน้า",
    }
)


def render(tmp_path: Path) -> Path:
    return docgen.render(MINUTES, tmp_path / "minutes.docx", model="deepseek-chat")


def _runs(path: Path) -> list[etree._Element]:
    """Runs that carry text. The page break before the action items is a run
    with no text and nothing to style."""
    with zipfile.ZipFile(path) as zf:
        root = etree.fromstring(zf.read("word/document.xml"))
    return [r for r in root.findall(f".//{{{W}}}r") if r.find(f"{{{W}}}t") is not None]


def test_renders_a_readable_docx(tmp_path: Path) -> None:
    out = render(tmp_path)
    text = "\n".join(p.text for p in Document(str(out)).paragraphs)

    assert MINUTES.title in text
    assert "สรุปผู้บริหาร / Executive summary" in text
    assert "ที่ประชุมทบทวนความคืบหน้าไตรมาส 3" in text
    assert "Generated by Sarai AI · deepseek-chat" in text


def test_every_run_sets_the_complex_script_font_and_size(tmp_path: Path) -> None:
    runs = _runs(render(tmp_path))
    assert runs, "document has no runs"

    for run in runs:
        rpr = run.find(f"{{{W}}}rPr")
        assert rpr is not None
        rfonts = rpr.find(f"{{{W}}}rFonts")
        assert rfonts is not None
        assert rfonts.get(f"{{{W}}}cs") == "Sarabun"
        assert rfonts.get(f"{{{W}}}ascii") == "Sarabun"

        sz = rpr.find(f"{{{W}}}sz")
        sz_cs = rpr.find(f"{{{W}}}szCs")
        assert sz is not None and sz_cs is not None
        # Latin and Thai must be the same size, or the two scripts disagree.
        assert sz.get(f"{{{W}}}val") == sz_cs.get(f"{{{W}}}val")


def test_action_items_render_as_a_table_with_their_evidence(tmp_path: Path) -> None:
    doc = Document(str(render(tmp_path)))
    tables = doc.tables
    assert len(tables) >= 2  # attendees, then action items

    action_table = tables[-1]
    header = [c.text for c in action_table.rows[0].cells]
    assert header[0].startswith("สิ่งที่ต้องทำ")

    body = "\n".join(c.text for row in action_table.rows[1:] for c in row.cells)
    assert "ส่งเอกสาร PDPA" in body
    assert "คุณมาลี" in body
    assert "เดี๋ยวจะส่งให้ภายในวันศุกร์" in body


def test_missing_optional_sections_do_not_break_rendering(tmp_path: Path) -> None:
    sparse = MinutesJSON(title="ประชุมสั้น")
    out = docgen.render(sparse, tmp_path / "sparse.docx", model="m")
    assert out.is_file()
    assert "ประชุมสั้น" in Document(str(out)).paragraphs[0].text


def test_font_obfuscation_round_trips() -> None:
    """ECMA-376 obfuscation is a self-inverse XOR; if that ever stops holding,
    Word will reject the embedded font with no useful error."""
    original = bytes(range(64))
    guid = uuid.uuid4()

    scrambled = fonts.obfuscate(original, guid)
    assert scrambled != original
    assert scrambled[32:] == original[32:]  # only the header is touched
    assert fonts.obfuscate(scrambled, guid) == original


def test_fonts_embed_when_present_and_are_skipped_when_absent(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    doc_path = tmp_path / "embedded.docx"
    fake_dir = tmp_path / "fonts"
    fake_dir.mkdir()
    (fake_dir / "Sarabun-Regular.ttf").write_bytes(b"\x00\x01\x02\x03" * 32)
    monkeypatch.setattr(fonts, "FONTS_DIR", fake_dir)

    docgen.render(MINUTES, doc_path, model="m")
    with zipfile.ZipFile(doc_path) as zf:
        names = zf.namelist()
        font_table = zf.read("word/fontTable.xml").decode()
    assert "word/fonts/font1.odttf" in names
    assert "embedRegular" in font_table

    # Without the files the document still renders; it just names the font.
    monkeypatch.setattr(fonts, "FONTS_DIR", tmp_path / "nothing-here")
    plain = tmp_path / "plain.docx"
    docgen.render(MINUTES, plain, model="m")
    with zipfile.ZipFile(plain) as zf:
        assert not [n for n in zf.namelist() if n.endswith(".odttf")]
