"""Emit web/src/types.ts from the Pydantic models in sarai/models.py.

Run via `make types`. CI runs it and fails if the working tree changes, so the
frontend types can never drift from the backend contract.

Deliberately hand-rolled rather than JSON-Schema-based: the models use a small
type vocabulary, and the output stays readable enough to review in a diff.
"""

from __future__ import annotations

import argparse
import enum
import sys
import types
import typing
from pathlib import Path
from typing import TypeGuard

from pydantic import BaseModel

# Running this file directly puts scripts/ on sys.path, not the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sarai import models  # noqa: E402

HEADER = """// GENERATED by scripts/gen_types.py from sarai/models.py -- do not hand-edit.
// Regenerate with `make types`.
"""


def _is_model(obj: object) -> TypeGuard[type[BaseModel]]:
    return isinstance(obj, type) and issubclass(obj, BaseModel) and obj is not BaseModel


def _is_enum(obj: object) -> TypeGuard[type[enum.Enum]]:
    return isinstance(obj, type) and issubclass(obj, enum.Enum)


def ts_type(annotation: object) -> str:
    if annotation is None or annotation is type(None):
        return "null"
    if annotation is str:
        return "string"
    if annotation in (int, float):
        return "number"
    if annotation is bool:
        return "boolean"
    if _is_enum(annotation) or _is_model(annotation):
        return annotation.__name__

    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)

    if origin in (types.UnionType, typing.Union):
        parts = [ts_type(a) for a in args]
        # Collapse `X | null | null`, keep declaration order otherwise.
        seen: list[str] = []
        for p in parts:
            if p not in seen:
                seen.append(p)
        return " | ".join(seen)
    if origin in (list, set, frozenset, tuple):
        inner = ts_type(args[0]) if args else "unknown"
        return f"{inner}[]" if " " not in inner else f"({inner})[]"
    if origin is dict:
        key = "string"
        value = ts_type(args[1]) if len(args) > 1 else "unknown"
        return f"Record<{key}, {value}>"
    if annotation is typing.Any:
        return "unknown"
    raise TypeError(f"gen_types has no TypeScript mapping for {annotation!r}")


def render_enum(enum_cls: type[enum.Enum]) -> str:
    values = " | ".join(f'"{member.value}"' for member in enum_cls)
    return f"export type {enum_cls.__name__} = {values};"


def render_model(model: type[BaseModel]) -> str:
    lines = [f"export interface {model.__name__} {{"]
    for name, field in model.model_fields.items():
        rendered = ts_type(field.annotation)
        # Optional in TS means "may be absent"; a nullable-with-default field is
        # both absent-able on the wire and null-able, so mark it `?`.
        optional = "" if field.is_required() else "?"
        lines.append(f"  {name}{optional}: {rendered};")
    lines.append("}")
    return "\n".join(lines)


def collect() -> tuple[list[type[enum.Enum]], list[type[BaseModel]]]:
    enums: list[type[enum.Enum]] = []
    model_types: list[type[BaseModel]] = []
    for name in dir(models):
        obj = getattr(models, name)
        if getattr(obj, "__module__", None) != models.__name__:
            continue
        if _is_enum(obj):
            enums.append(obj)
        elif _is_model(obj):
            model_types.append(obj)
    return enums, model_types


def _sort_models(model_types: list[type[BaseModel]]) -> list[type[BaseModel]]:
    """Base classes first so subclass interfaces read top-down."""
    return sorted(model_types, key=lambda m: (len(m.__mro__), m.__name__))


def generate() -> str:
    enums, model_types = collect()
    blocks = [HEADER.rstrip()]
    blocks.extend(render_enum(e) for e in sorted(enums, key=lambda e: e.__name__))
    blocks.extend(render_model(m) for m in _sort_models(model_types))
    return "\n\n".join(blocks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "web" / "src" / "types.ts",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the file on disk differs (used in CI)",
    )
    args = parser.parse_args()

    content = generate()
    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if current != content:
            print(f"{args.out} is out of date. Run `make types`.", file=sys.stderr)
            return 1
        print(f"{args.out} is up to date.")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content, encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
