// GENERATED by scripts/gen_types.py from sarai/models.py -- do not hand-edit.
// Regenerate with `make types`.

export type JobKind = "transcribe" | "summarize";

export type LanguageHint = "auto" | "th" | "en";

export type Stage = "queued" | "normalizing" | "diarizing" | "transcribing" | "awaiting_review" | "summarizing" | "rendering" | "done" | "failed";

export interface ActionItem {
  task: string;
  owner?: string | null;
  due?: string | null;
  source_quote: string;
}

export interface Attendee {
  name: string;
  role?: string | null;
}

export interface Decision {
  decision: string;
  rationale?: string | null;
}

export interface DiscussionTopic {
  topic: string;
  points?: string[];
  speakers?: string[];
}

export interface ErrorResponse {
  detail: string;
}

export interface HealthResponse {
  api: boolean;
  db: boolean;
  worker_heartbeat?: string | null;
  worker_alive?: boolean;
  llm: string;
}

export interface Job {
  id: string;
  meeting_id: string;
  kind: JobKind;
  stage: Stage;
  progress?: number;
  detail?: string | null;
  error?: string | null;
  attempts?: number;
  claimed_by?: string | null;
  claimed_at?: string | null;
  updated_at: string;
}

export interface JobEvent {
  job_id: string;
  stage: Stage;
  progress: number;
  detail?: string | null;
  error?: string | null;
}

export interface Meeting {
  id: string;
  title: string;
  meeting_date?: string | null;
  source_file: string;
  audio_path: string;
  duration_sec?: number | null;
  language_hint?: LanguageHint;
  glossary?: string[];
  attendees?: Attendee[];
  auto_summarize?: boolean;
  created_at: string;
}

export interface MeetingCreated {
  meeting_id: string;
  job_id: string;
}

export interface MeetingListItem {
  meeting: Meeting;
  stage?: Stage | null;
  job_id?: string | null;
  progress?: number;
  has_transcript?: boolean;
  has_summary?: boolean;
}

export interface MinutesJSON {
  title: string;
  meeting_date?: string | null;
  attendees?: Attendee[];
  summary?: string;
  agenda?: string[];
  discussion?: DiscussionTopic[];
  decisions?: Decision[];
  action_items?: ActionItem[];
  open_questions?: string[];
  next_meeting?: string | null;
}

export interface Segment {
  id: number;
  start: number;
  end: number;
  speaker: string;
  text: string;
  confidence?: number | null;
}

export interface SpeakersUpdate {
  speakers: Record<string, string>;
}

export interface SummarizeInput {
  title?: string | null;
  meeting_date?: string | null;
  attendees?: Attendee[];
  glossary?: string[];
  segments?: Segment[];
  speakers?: Record<string, string>;
}

export interface SummaryResponse {
  data: MinutesJSON;
  model: string;
  has_document?: boolean;
  created_at: string;
}

export interface TranscriptResponse {
  segments: Segment[];
  speakers: Record<string, string>;
  edited?: boolean;
}

export interface TranscriptUpdate {
  segments: Segment[];
}

export interface MeetingDetail {
  meeting: Meeting;
  stage?: Stage | null;
  job_id?: string | null;
  progress?: number;
  has_transcript?: boolean;
  has_summary?: boolean;
  error?: string | null;
  detail?: string | null;
}
